#Genre
INSERT INTO eGames.genre (version, name) VALUES (0, 'Point-and-click');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Fighting');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Shooter');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Music');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Platform');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Puzzle');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Racing');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Real Time Strategy (RTS)');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Role-playing (RPG)');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Simulator');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Sport');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Strategy');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Turn-based strategy (TBS)');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Tactical');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Hack and slash/Beat ''em up');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Quiz/Trivia');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Pinball');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Adventure');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Indie');
INSERT INTO eGames.genre (version, name) VALUES (0, 'Arcade');
