INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'alvrodlag/personalGames/Call of Duty: Black Ops III/freedvdcover_call-of-duty-black-ops-iii-pal-cover-xbox-one-610x339.jpg', 1);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'alvrodlag/personalGames/Call of Duty: Black Ops III/image_the_witcher_3_wild_hunt-22370-2651_00061.jpg', 1);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'alvrodlag/personalGames/Grand Theft Auto V/ec98b24f25993c45f1cfd97031438dbf.jpg', 2);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'alvrodlag/personalGames/Grand Theft Auto V/grand-theft-auto-v-microsoft-xbox-one-2014-mint-complete-gta-5-free-ship-faa0659f55901fe2afb35bf32d743a43.jpg', 2);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'alvrodlag/personalGames/Star Wars: Battlefront 2/65050-star-wars-battlefront-iii.png', 3);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'alvrodlag/personalGames/Star Wars: Battlefront 2/6star_wars_battlefront_3_xbox_one_front_cover_by_creativeanthony-d9ll3qj.png', 3);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'bonbarull/personalGames/FIFA 17/FIFA-17-600213.jpg', 4);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'bonbarull/personalGames/NBA 2K16/$_1.jpg', 5);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'laucazval/personalGames/Assassin''s Creed IV: Black Flag/assassins_creed_iv_4_black_flag_raw.jpg', 6);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'marcorgue/personalGames/The Last of Us Remastered/TLoU.jpg', 8);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'marcorgue/personalGames/Uncharted 4: A Thief''s End/Uncharted-4-Standard-Edition-v2.png', 7);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'marcorgue/personalGames/Uncharted 4: A Thief''s End/UnchartedCoverMockUP.png', 7);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'sanespmer/personalGames/Far Cry 4/10313342_674782539226049_3266324310317627304_n.jpg', 10);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'sanespmer/personalGames/The Witcher 3: Wild Hunt/The-Wicther-3-3.jpg', 11);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'letmonguz/personalGames/NBA 2K16/15-09-16-10-43_0_81bspreknfl._sx425_.jpg', 12);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'carramcor/personalGames/Far Cry: Primal/freedvdcover_far-cry-primal-2016-ps4-custom-1-610x357.jpg', 14);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'josbergri/personalGames/Watch Dogs 2/watch-dogs-2-playstation4-qatar-ps4.jpg', 15);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'estadoven/personalGames/Call of Duty: Black Ops III/freedvdcover_call-of-duty-black-ops-iii-pal-cover-xbox-one-610x339.jpg', 17);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'josbergri/personalGames/Call of Duty: Black Ops III/image_the_witcher_3_wild_hunt-22370-2651_00061.jpg', 18);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'marcorgue/personalGames/Uncharted 4: A Thief''s End/Uncharted-4-Standard-Edition-v2.png', 19);
INSERT INTO eGames.image (version, path_url, personal_game_id) VALUES (0, 'sanespmer/personalGames/Rocket League/Rocket League.png', 21);