#Personal games
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Ha salido un nuevo juego de CoD y este ya no lo quiero. Está bien. La carátula contiene todos los papeles.",0,"Fijo", 110, 1,1);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Ya me pasé el modo historia y no tengo suscripción para poder jugar online, por eso lo quiero cambiar. Es un juegazo.",0,"Fijo", 176, 1,5);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Lo cambio por algún CoD, ya que este juego no me ha terminado de convencer",0,"Fijo", 354, 1,5);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Lo intercambio momentáneamente, ya que ahora juego más a juegos con modo historia.",0,"Temporal", 583, 2,2);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Lo intercambio momentáneamente, ya que ahora juego más a juegos con modo historia.",0,"Temporal", 691, 2,NULL);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Lo cambio porque me lo regalaron y no me gustó, pero quizás a un fan de AC le guste.",0,"Fijo", 732, 3,NULL);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Lo intercambio por otro momentánemanete porque quiero pasarme otros juegos, pero lo quiero de vuelta, porque es una joya de juego.",0,"Temporal", 182, 4,2);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Lo intercambio por otro momentánemanete porque quiero pasarme otros juegos, pero lo quiero de vuelta, porque es una joya de juego.",0,"Temporal", 237, 4,NULL);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Lo intercambio porque me ha decepcionado mucho, si alguien lo quiere...",0,"Fijo", 307, 4,3);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Lo compré, pero apenas juego, por eso lo quiero cambiar por otro",0,"Fijo", 310, 5,NULL);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Creía que iba a ser de otra forma, y no me gusta a pesar de que es un juegazo",0,"Fijo", 315, 5,1);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Ya compré el NBA 2K17, así que lo cambiaría por otro tipo de juego.",0,"Fijo", 326, 6,3);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Este juego me venía con la play, ya lo pasé y lo quiero cambiar",0,"Fijo", 572, 6,4);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Ya lo pasé, pero quiero el juego de vuelta, porque me divierto jugando de vez en cuando.",0,"Temporal", 719, 7,NULL);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Ya me lo he pasado.",0,"Fijo", 1819, 8,5);
INSERT INTO personal_game (description, number_of_views, type, game_id, user_id, exchange_id) VALUES ("Mi tío me lo regaló, pero es una verdadera basura para mí, que soy fan del Fifa",0,"Fijo", 4374, 9,4);
