#Personal games
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Ha salido un nuevo juego de CoD y este ya no lo quiero. Está bien. La carátula contiene todos los papeles.', 0, 'Fijo', 1, 110, 1);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Ya me pasé el modo historia y no tengo suscripción para poder jugar online, por eso lo quiero cambiar. Es un juegazo.', 0, 'Fijo', 5, 176, 1);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Lo cambio por algún CoD, ya que este juego no me ha terminado de convencer', 0, 'Fijo', 5, 354, 1);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Lo intercambio momentáneamente, ya que ahora juego más a juegos con modo historia.', 0, 'Temporal', 2, 583, 2);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Lo intercambio por otro momentánemanete porque quiero pasarme otros juegos, pero lo quiero de vuelta, porque es una joya de juego.', 0, 'Temporal', 2, 182, 4);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Lo intercambio por otro momentánemanete porque quiero pasarme otros juegos, pero lo quiero de vuelta, porque es una joya de juego.', 0, 'Temporal', null, 237, 4);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Lo intercambio porque me ha decepcionado mucho, si alguien lo quiere...', 0, 'Fijo', 3, 307, 4);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Lo compré, pero apenas juego, por eso lo quiero cambiar por otro', 0, 'Fijo', null, 310, 5);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Creía que iba a ser de otra forma, y no me gusta a pesar de que es un juegazo', 0, 'Fijo', 1, 315, 5);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Ya compré el NBA 2K17, así que lo cambiaría por otro tipo de juego.', 0, 'Fijo', 3, 326, 6);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Este juego me venía con la play, ya lo pasé y lo quiero cambiar', 0, 'Fijo', 4, 572, 6);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Ya lo pasé, pero quiero el juego de vuelta, porque me divierto jugando de vez en cuando.', 0, 'Temporal', null, 719, 7);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Ya me lo he pasado.', 0, 'Fijo', 5, 1819, 8);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Mi tío me lo regaló, pero es una verdadera basura para mí, que soy fan del Fifa', 0, 'Fijo', 4, 4374, 9);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Me he cansado de él, como me pasa con todos los CoD', 0, 'Fijo', null, 110, 9);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Juego muy bueno, pero ahora prefiero otros tipos de juegos', 0, 'Fijo', null, 110, 8);
INSERT INTO eGames.personal_game (version, description, number_of_views, type, exchange_id, game_id, user_id) VALUES (0, 'Grandisimo juego, pero ya me lo he pasado y quiero disfrutar otros', 0, 'Fijo', null, 182, 6);
