#Platforms
INSERT IGNORE INTO platform (id, name) VALUES (3, 'Linux');
INSERT IGNORE INTO platform (id, name) VALUES (4, 'Nintendo 64');
INSERT IGNORE INTO platform (id, name) VALUES (5, 'Wii');
INSERT IGNORE INTO platform (id, name) VALUES (6, 'PC (Microsoft Windows)');
INSERT IGNORE INTO platform (id, name) VALUES (7, 'PlayStation');
INSERT IGNORE INTO platform (id, name) VALUES (8, 'PlayStation 2');
INSERT IGNORE INTO platform (id, name) VALUES (9, 'PlayStation 3');
INSERT IGNORE INTO platform (id, name) VALUES (11, 'Xbox');
INSERT IGNORE INTO platform (id, name) VALUES (12, 'Xbox 360');
INSERT IGNORE INTO platform (id, name) VALUES (13, 'PC DOS');
INSERT IGNORE INTO platform (id, name) VALUES (14, 'Mac');
INSERT IGNORE INTO platform (id, name) VALUES (15, 'Commodore C64/128');
INSERT IGNORE INTO platform (id, name) VALUES (16, 'Amiga');
INSERT IGNORE INTO platform (id, name) VALUES (18, 'Nintendo Entertainment System (NES)');
INSERT IGNORE INTO platform (id, name) VALUES (19, 'Super Nintendo Entertainment System (SNES)');
INSERT IGNORE INTO platform (id, name) VALUES (20, 'Nintendo DS');
INSERT IGNORE INTO platform (id, name) VALUES (21, 'Nintendo GameCube');
INSERT IGNORE INTO platform (id, name) VALUES (22, 'Game Boy Color');
INSERT IGNORE INTO platform (id, name) VALUES (23, 'Dreamcast');
INSERT IGNORE INTO platform (id, name) VALUES (24, 'Game Boy Advance');
INSERT IGNORE INTO platform (id, name) VALUES (25, 'Amstrad CPC');
INSERT IGNORE INTO platform (id, name) VALUES (26, 'ZX Spectrum');
INSERT IGNORE INTO platform (id, name) VALUES (27, 'MSX');
INSERT IGNORE INTO platform (id, name) VALUES (29, 'Sega Mega Drive/Genesis');
INSERT IGNORE INTO platform (id, name) VALUES (30, 'Sega 32X');
INSERT IGNORE INTO platform (id, name) VALUES (32, 'Sega Saturn');
INSERT IGNORE INTO platform (id, name) VALUES (33, 'Game Boy');
INSERT IGNORE INTO platform (id, name) VALUES (34, 'Android');
INSERT IGNORE INTO platform (id, name) VALUES (35, 'Sega Game Gear');
INSERT IGNORE INTO platform (id, name) VALUES (36, 'Xbox Live Arcade');
INSERT IGNORE INTO platform (id, name) VALUES (37, 'Nintendo 3DS');
INSERT IGNORE INTO platform (id, name) VALUES (38, 'PlayStation Portable');
INSERT IGNORE INTO platform (id, name) VALUES (39, 'iOS');
INSERT IGNORE INTO platform (id, name) VALUES (41, 'Wii U');
INSERT IGNORE INTO platform (id, name) VALUES (42, 'N-Gage');
INSERT IGNORE INTO platform (id, name) VALUES (44, 'Tapwave Zodiac');
INSERT IGNORE INTO platform (id, name) VALUES (45, 'PlayStation Network');
INSERT IGNORE INTO platform (id, name) VALUES (46, 'PlayStation Vita');
INSERT IGNORE INTO platform (id, name) VALUES (47, 'Virtual Console (Nintendo)');
INSERT IGNORE INTO platform (id, name) VALUES (48, 'PlayStation 4');
INSERT IGNORE INTO platform (id, name) VALUES (49, 'Xbox One');
INSERT IGNORE INTO platform (id, name) VALUES (50, '3DO Interactive Multiplayer');
INSERT IGNORE INTO platform (id, name) VALUES (51, 'Family Computer Disk System');
INSERT IGNORE INTO platform (id, name) VALUES (52, 'Arcade');
INSERT IGNORE INTO platform (id, name) VALUES (53, 'MSX2');
INSERT IGNORE INTO platform (id, name) VALUES (55, 'Mobile');
INSERT IGNORE INTO platform (id, name) VALUES (56, 'WiiWare');
INSERT IGNORE INTO platform (id, name) VALUES (57, 'WonderSwan');
INSERT IGNORE INTO platform (id, name) VALUES (58, 'Super Famicom');
INSERT IGNORE INTO platform (id, name) VALUES (59, 'Atari 2600');
INSERT IGNORE INTO platform (id, name) VALUES (60, 'Atari 7800');
INSERT IGNORE INTO platform (id, name) VALUES (61, 'Atari Lynx');
INSERT IGNORE INTO platform (id, name) VALUES (62, 'Atari Jaguar');
INSERT IGNORE INTO platform (id, name) VALUES (63, 'Atari ST/STE');
INSERT IGNORE INTO platform (id, name) VALUES (64, 'Sega Master System');
INSERT IGNORE INTO platform (id, name) VALUES (65, 'Atari 8-bit');
INSERT IGNORE INTO platform (id, name) VALUES (66, 'Atari 5200');
INSERT IGNORE INTO platform (id, name) VALUES (67, 'Intellivision');
INSERT IGNORE INTO platform (id, name) VALUES (68, 'ColecoVision');
INSERT IGNORE INTO platform (id, name) VALUES (69, 'BBC Microcomputer System');
INSERT IGNORE INTO platform (id, name) VALUES (70, 'Vectrex');
INSERT IGNORE INTO platform (id, name) VALUES (71, 'Commodore VIC-20');
INSERT IGNORE INTO platform (id, name) VALUES (72, 'Ouya');
INSERT IGNORE INTO platform (id, name) VALUES (73, 'BlackBerry OS');
INSERT IGNORE INTO platform (id, name) VALUES (74, 'Windows Phone');
INSERT IGNORE INTO platform (id, name) VALUES (75, 'Apple II');
INSERT IGNORE INTO platform (id, name) VALUES (77, 'Sharp X1');
INSERT IGNORE INTO platform (id, name) VALUES (78, 'Sega CD');
INSERT IGNORE INTO platform (id, name) VALUES (79, 'Neo Geo MVS');
INSERT IGNORE INTO platform (id, name) VALUES (80, 'Neo Geo AES');
INSERT IGNORE INTO platform (id, name) VALUES (82, 'Web browser');
INSERT IGNORE INTO platform (id, name) VALUES (84, 'SG-1000');
INSERT IGNORE INTO platform (id, name) VALUES (85, 'Donner Model 30');
INSERT IGNORE INTO platform (id, name) VALUES (86, 'TurboGrafx-16/PC Engine');
INSERT IGNORE INTO platform (id, name) VALUES (87, 'Virtual Boy');
INSERT IGNORE INTO platform (id, name) VALUES (88, 'Odyssey');
INSERT IGNORE INTO platform (id, name) VALUES (89, 'Microvision');
INSERT IGNORE INTO platform (id, name) VALUES (90, 'Commodore PET');
INSERT IGNORE INTO platform (id, name) VALUES (91, 'Bally Astrocade');
INSERT IGNORE INTO platform (id, name) VALUES (92, 'SteamOS');
INSERT IGNORE INTO platform (id, name) VALUES (93, 'Commodore 16');
INSERT IGNORE INTO platform (id, name) VALUES (94, 'Commodore Plus/4');
INSERT IGNORE INTO platform (id, name) VALUES (95, 'PDP-1');
INSERT IGNORE INTO platform (id, name) VALUES (96, 'PDP-10');
INSERT IGNORE INTO platform (id, name) VALUES (97, 'PDP-8');
INSERT IGNORE INTO platform (id, name) VALUES (98, 'DEC GT40');
INSERT IGNORE INTO platform (id, name) VALUES (99, 'Family Computer');
INSERT IGNORE INTO platform (id, name) VALUES (100, 'Analogue electronics');
INSERT IGNORE INTO platform (id, name) VALUES (101, 'Ferranti Nimrod Computer');
INSERT IGNORE INTO platform (id, name) VALUES (102, 'EDSAC');
INSERT IGNORE INTO platform (id, name) VALUES (103, 'PDP-7');
INSERT IGNORE INTO platform (id, name) VALUES (104, 'HP 2100');
INSERT IGNORE INTO platform (id, name) VALUES (105, 'HP 3000');
INSERT IGNORE INTO platform (id, name) VALUES (106, 'SDS Sigma 7');
INSERT IGNORE INTO platform (id, name) VALUES (107, 'Call-A-Computer time-shared mainframe computer system');
INSERT IGNORE INTO platform (id, name) VALUES (108, 'PDP-11');
INSERT IGNORE INTO platform (id, name) VALUES (109, 'CDC Cyber 70');
INSERT IGNORE INTO platform (id, name) VALUES (110, 'PLATO');
INSERT IGNORE INTO platform (id, name) VALUES (111, 'Imlac PDS-1');
INSERT IGNORE INTO platform (id, name) VALUES (112, 'Microcomputer');
INSERT IGNORE INTO platform (id, name) VALUES (113, 'OnLive Game System');
INSERT IGNORE INTO platform (id, name) VALUES (114, 'Amiga CD32');
INSERT IGNORE INTO platform (id, name) VALUES (115, 'Apple IIGS');
INSERT IGNORE INTO platform (id, name) VALUES (116, 'Acorn Archimedes');
INSERT IGNORE INTO platform (id, name) VALUES (117, 'Philips CD-i');
INSERT IGNORE INTO platform (id, name) VALUES (118, 'FM Towns');
INSERT IGNORE INTO platform (id, name) VALUES (119, 'Neo Geo Pocket');
INSERT IGNORE INTO platform (id, name) VALUES (120, 'Neo Geo Pocket Color');
INSERT IGNORE INTO platform (id, name) VALUES (121, 'Sharp X68000');
INSERT IGNORE INTO platform (id, name) VALUES (122, 'Nuon');
INSERT IGNORE INTO platform (id, name) VALUES (123, 'WonderSwan Color');
INSERT IGNORE INTO platform (id, name) VALUES (124, 'SwanCrystal');
INSERT IGNORE INTO platform (id, name) VALUES (125, 'PC-8801');
INSERT IGNORE INTO platform (id, name) VALUES (126, 'TRS-80');
INSERT IGNORE INTO platform (id, name) VALUES (127, 'Fairchild Channel F');
INSERT IGNORE INTO platform (id, name) VALUES (128, 'PC Engine SuperGrafx');
INSERT IGNORE INTO platform (id, name) VALUES (129, 'Texas Instruments TI-99');
INSERT IGNORE INTO platform (id, name) VALUES (130, 'Nintendo Switch');
INSERT IGNORE INTO platform (id, name) VALUES (131, 'Nintendo PlayStation');
INSERT IGNORE INTO platform (id, name) VALUES (132, 'Amazon Fire TV');
INSERT IGNORE INTO platform (id, name) VALUES (133, 'Philips Videopac G7000');
INSERT IGNORE INTO platform (id, name) VALUES (134, 'Acorn Electron');
