#User 
INSERT INTO eGames.user (version, city, country, state, street, zip, n_exchanges, name, profile_picture, reputation, surname, user_account_id) VALUES (0, 'Aracena', 'España', 'Huelva', 'Calle 1', '21200', 0, 'User1', 'username1/profilePictures/nobody_m.original.jpg', 0, 'Surname1', 1);
INSERT INTO eGames.user (version, city, country, state, street, zip, n_exchanges, name, profile_picture, reputation, surname, user_account_id) VALUES (0, 'Sevilla', 'España', 'Sevilla', 'Calle 2', '41012', 0, 'User2', 'username2/profilePictures/47476486-profile-pictures.png', 0, 'Surname2', 2);
INSERT INTO eGames.user (version, city, country, state, street, zip, n_exchanges, name, profile_picture, reputation, surname, user_account_id) VALUES (0, 'Barcelona', 'España', 'Cataluña', 'Calle 3', '08037', 0, 'User3', null, 0, 'Surname3', 3);
INSERT INTO eGames.user (version, city, country, state, street, zip, n_exchanges, name, profile_picture, reputation, surname, user_account_id) VALUES (0, 'Madrid', 'España', 'Madrid', 'Calle 4', '28005', 0, 'User4', null, 0, 'Surname4', 4);
INSERT INTO eGames.user (version, city, country, state, street, zip, n_exchanges, name, profile_picture, reputation, surname, user_account_id) VALUES (0, 'Huelva', 'España', 'Huelva', 'Calle 5', '21004', 0, 'User5', null, 0, 'Surname5', 5);
INSERT INTO eGames.user (version, city, country, state, street, zip, n_exchanges, name, profile_picture, reputation, surname, user_account_id) VALUES (0, 'Puerto Moral', 'España', 'Huelva', 'Calle 6', '21209', 0, 'User6', null, 0, 'Surname6', 6);
INSERT INTO eGames.user (version, city, country, state, street, zip, n_exchanges, name, profile_picture, reputation, surname, user_account_id) VALUES (0, 'Sevilla', 'España', 'Sevilla', 'Calle 7', '41070', 0, 'User7', null, 0, 'Surname7', 7);
INSERT INTO eGames.user (version, city, country, state, street, zip, n_exchanges, name, profile_picture, reputation, surname, user_account_id) VALUES (0, 'Dos Hermanas', 'España', 'Sevilla', 'Calle 8', '41700', 0, 'User8', null, 0, 'Surname8', 8);
INSERT INTO eGames.user (version, city, country, state, street, zip, n_exchanges, name, profile_picture, reputation, surname, user_account_id) VALUES (0, 'Utrera', 'España', 'Sevilla', 'Calle 9', '41710', 0, 'User9', null, 0, 'Surname9', 9);
INSERT INTO eGames.user (version, city, country, state, street, zip, n_exchanges, name, profile_picture, reputation, surname, user_account_id) VALUES (0, 'San Juan De Aznalfarache', 'España', 'Sevilla', 'Calle 10', '41920', 0, 'User10', null, 0, 'Surname10', 10);
